Feature/tg/admin gabrielvazquez
BaSP-m2022/diego-trackgenix-server pull request #3
Opened 2022-05-10 19:48 UTC by gavafue

BASP-TG: My work is ready to be reviewed. Thank you so much

2022-05-10 20:45 UTC, LastStance21 commented on src/resources/admins.js
> +module.exports = router;
This could be written as "export default router;". I don't think, that could affect to the general workflow

2022-05-10 20:46 UTC, LastStance21 approved these changes
Everything it's ok.

2022-05-10 20:54 UTC, paurinaldi requested changes
adding to what dany said about the export, you should also check the way in which you are importing, it should be the same as the way you import express on the index, all over the files (except the json files on index).
for example:
const adminsRouter = require('./resources/admins');  should be:
 import adminsRouter from './resources/admins'
 the same with express, adminList, and fs on admins.js.

2022-05-10 22:25 UTC, paurinaldi approved these changes

2022-05-10 23:59 UTC, DiegoCastr0 requested changes

2022-05-10 23:59 UTC, DiegoCastr0 commented on package.json
> +    "begin":"nodemon src/index.js",
Why do we need this line? This should be handled by the start script

2022-05-10 23:59 UTC, DiegoCastr0 commented on src/index.js
> +    data: adminsList,
We should move this getAll logic inside the adminsRouter

2022-05-10 23:59 UTC, DiegoCastr0 commented on src/resources/admins.js
> +  const arrayOfFiltersKeyNames = Object.getOwnPropertyNames(req.query);
Please use Object.keys instead of Object.getOwnPropertyNames, we are not setting not enumerable properties inside the req.query object.

2022-05-10 23:59 UTC, DiegoCastr0 commented on src/resources/admins.js
> +                        === objectOfFilters[key].toLowerCase();
This line must have two spaces (one tab) of difference from the line above.

2022-05-10 23:59 UTC, DiegoCastr0 commented on src/resources/admins.js
> +  const adminListUpdated = adminsList.map((persona) => {
Replace this persona with an a

2022-05-12 01:10 UTC, DiegoCastr0 approved these changes

2022-05-12 01:10 UTC, merged