BaSP-TG: Ready to be reviewed.
BaSP-m2022/diego-trackgenix-server pull request #4
Opened 2022-05-10 19:49 UTC by juanramosss

2022-05-10 21:04 UTC, paurinaldi requested changes

2022-05-10 21:04 UTC, paurinaldi commented on src/index.js
> +
I would delete this empty space.
Also, I think on the original file, the order was const app and const port below. I would import the router below import express from 'express', and using the same syntax, as told by Diego today, meaning:  import adminRouter from './resources/admins'

2022-05-10 21:04 UTC, paurinaldi commented on src/resources/admins.js
> +
the first 3 const should be imported as explained on the other comment aswell.

2022-05-10 21:04 UTC, paurinaldi commented on src/resources/admins.js
> +module.exports = router;
as well as the imports, we need to change the way in which we export to:

export default router;

2022-05-10 22:57 UTC, paurinaldi approved these changes

2022-05-10 23:46 UTC, DiegoCastr0 commented on src/resources/admins.js
> +
I agree, we should be using import syntaxes here

2022-05-10 23:52 UTC, DiegoCastr0 requested changes
Please correct the requested changes and change the name of the pull request

2022-05-10 23:52 UTC, DiegoCastr0 commented on src/index.js
>    });
We should move this getAll to the adminsRouter

2022-05-10 23:52 UTC, DiegoCastr0 commented on src/resources/admins.js
> +router.get('/getById/:id', (req, res) => {
Is not necessary the "/getById" in the route since "/" and "/:id" are two completely different routes

2022-05-10 23:52 UTC, DiegoCastr0 commented on src/resources/admins.js
> +  const admin = admins.find((admin1) => admin1.id === adminId);
Replace this admin1 for an a

2022-05-10 23:52 UTC, DiegoCastr0 commented on src/resources/admins.js
> +router.post('/add', (req, res) => {
Is not necessary the "/add" in the route since we are using the post method

2022-05-10 23:52 UTC, DiegoCastr0 commented on src/resources/admins.js
> +router.delete('/delete/:id', (req, res) => {
Is not necessary the "/delete" in the route since we are using the delete method

2022-05-12 02:32 UTC, DiegoCastr0 approved these changes

2022-05-12 02:32 UTC, merged